name: Cleanup Files and Directories

on:
  push:
    branches: [ master ]  

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Delete files and directories
        run: |
          # Replace the lines below with your files/directories
          ls -la
          [ -d ./e2e/ ] && rm -rf ./e2e/
          [ -d ./generator/ ] && rm -rf ./generator/
          [ -d ./src/es/components/atoms/emotionPictures/corporate-/ ] && rm -rf ./src/es/components/atoms/emotionPictures/corporate-/
          [ -d ./src/es/components/atoms/emotionPictures/default-/ ] && rm -rf ./src/es/components/atoms/emotionPictures/default-/
          [ -d ./src/es/components/atoms/emotionPictures/with-button-/ ] && rm -rf ./src/es/components/atoms/emotionPictures/with-button-/
          [ -d ./src/es/components/atoms/emotionPictures/with-logo-/ ] && rm -rf ./src/es/components/atoms/emotionPictures/with-logo-/
          [ -d ./src/es/components/atoms/emotionPictures/with-title-/ ] && rm -rf ./src/es/components/atoms/emotionPictures/with-title-/
          [ -d ./src/es/components/atoms/emotionPictures/with-video-/ ] && rm -rf ./src/es/components/atoms/emotionPictures/with-video-/
          # [ -f ./src/es/components/atoms/emotionPictures/EmotionPictures.json ] && rm -f ./src/es/components/atoms/emotionPictures/EmotionPictures.json
          # [ -f ./src/es/components/atoms/emotionPictures/readme.md ] && rm -f ./src/es/components/atoms/emotionPictures/readme.md
          ls -la

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            # Only commit if there are changes
            git commit -m "Cleanup files and directories [skip ci]"
            git push
          fi
