name: Cleanup Files and Directories

on:
  push:
    branches: [ master ]  

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Delete files and directories
        run: |
          # Replace the lines below with your files/directories
          ls -la
          rm -rf ./e2e/ ./generator/ ./src/es/components/atoms/emotionPictures/corporate-/ ./src/es/components/atoms/emotionPictures/default-/ ./src/es/components/atoms/emotionPictures/with-button-/ ./src/es/components/atoms/emotionPictures/with-logo-/ ./src/es/components/atoms/emotionPictures/with-title-/ ./src/es/components/atoms/emotionPictures/with-video-/ 
          rm ./src/es/components/atoms/emotionPictures/EmotionPictures.json/ ./src/es/components/atoms/emotionPictures/readme.md/
          ls -la

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          # Only commit if there are changes
          git commit -m "Cleanup files and directories [skip ci]"
          git push
