name: Cleanup Files and Directories

on:
  push:
    branches: [ main ]  # Replace with your default branch name

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Delete files and directories
        run: |
          # Replace the lines below with your files/directories
          rm -f unwanted-file1.txt temporary-file.log
          rm -rf e2e generator

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          # Only commit if there are changes
          if ! git diff --quiet --exit-code; then
            git commit -m "Cleanup files and directories [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
